### ISSUE TITLE
bundlr failing with UNPREDICTABLE_GAS_LIMIT

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pybundlr#10]
I'm getting an issue on the bundlr CLI, trying to send MATIC to a bundlr node. It didn't happen a week ago or a month ago, but it's happening now.

Here's the command I used:
```console
bundlr fund 1479016 -h https://node1.bundlr.network --no-confirmation -c matic -w 8c14<rest-of-MATIC-private-key>
```

Here's the output:
```text
Loaded address: 0x8be6c8126c4383745c25f3b3ca76d73e3caf8544
Error whilst funding: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"cannot estimate gas; transaction may fail or may require manual gas limit","code":"UNPREDICTABLE_GAS_LIMIT","error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"error\":{\"code\":-32000,\"message\":\"gas required exceeds allowance (1301)\"},\"id\":55,\"jsonrpc\":\"2.0\"}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0xaf9b72c9c8\",\"maxPriorityFeePerGas\":\"0xaf9b72c9c8\",\"value\":\"0x169168\",\"from\":\"0x8be6c8126c4383745c25f3b3ca76d73e3caf8544\",\"to\":\"0xb4de0833771eae55040b698af5eb06d59e142c82\"}],\"id\":55,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://polygon-rpc.com/"},"method":"estimateGas","transaction":{"from":"0x8bE6c8126C4383745c25F3b3Ca76D73E3Caf8544","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0xaf9b72c9c8"},"maxFeePerGas":{"type":"BigNumber","hex":"0xaf9b72c9c8"},"to":"0xb4DE0833771eae55040b698aF5eB06d59E142C82","value":{"type":"BigNumber","hex":"0x169168"},"type":2,"accessList":null}}, tx={"to":{},"value":"0x169168","from":"0x8be6c8126c4383745c25f3b3ca76d73e3caf8544","type":2,"maxFeePerGas":{"type":"BigNumber","hex":"0xaf9b72c9c8"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0xaf9b72c9c8"},"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.7.0)
```

Note that that account holds more than enough MATIC to do this transaction.

This is a big problem: if bundlr doesn't work, pybundlr doesn't work.

**Comment by trentmc** [comment]
I just reported the issue to bundlr, via their discord.
https://discord.com/channels/864852288002850866/994913536906109029/1044691737320374312

**Comment by juanpablovs** [comment]
I just funded a node using the SDK with no issues

**Comment by trentmc** [comment]
Via help by the bundlr team on discord, I got to the bottom of the issue.

Summary: While my wallet had enough MATIC for the gas fees and to send, bundlr does a big multiplier based on max possible gas. And it seems that my wallet didn't have enough for that.

I tried with a different wallet that held way more MATIC, and it went through.

What this means: just hold more MATIC, the rest is fine. 

@juanpablovs this also explains why you didn't run into issues. If you had a wallet with less funds, you would have likely hit the same issue as me.

But it means we can close this issue:)

Details, from my [chat with bundlr support in discord](https://discord.com/channels/864852288002850866/1044691737320374312): 

----

Hello! I'm a big fan of bundlr:) I'm getting an issue on the bundlr CLI, trying to send MATIC to a bundlr node. It didn't happen a week ago or a month ago, but it's happening now.

Here's the command I used:
bundlr fund 1479016 -h https://node1.bundlr.network/ --no-confirmation -c matic -w 8c14<rest-of-MATIC-private-key>

Here's the output:
Loaded address: 0x8be6c8126c4383745c25f3b3ca76d73e3caf8544
Error whilst funding: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"cannot estimate gas; transaction may fail or may require manual gas limit","code":"UNPREDICTABLE_GAS_LIMIT","error":{"reason":"processing response error", ... <rest of output is in the uploaded file>

Note that that account holds more than enough MATIC to do this transaction.

Help?
Hello! I'm a big fan of bundlr:) I'm getting an issue on the bundlr CLI, trying to send MATIC to a bundlr node. It didn't happen a week ago or a month ago, but it's happening now.

Here's the command I used:
bundlr fund 1479016 -h https://node1.bundlr.network --no-confirmation -c matic -w 8c14<rest-of-MATIC-private-key>

Here's the output:
Expand
message.txt
3 KB
Jesse — Yesterday at 4:22 PM
Hey @trentmc0 , just a thread to keep things tidy
Jesse — Yesterday at 5:10 PM
what version of the bundlr client do you have installed? (you should be able to check via bundlr -v)
trentmc0 — Today at 12:58 PM
0.9.2
And I just ran a new install via npm install -g @bundlr-network/client, after that it still gives 0.9.2
I just tried running the command again today, to see if anything's changed. Interestingly, I get a different error this time: "insufficient funds for intrinsic transaction cost". But the wallet does have funds (though not a lot).
Here's the command, and error in detail
bundlr fund 1479016 -h https://node1.bundlr.network/ --no-confirmation -c matic -w 8c142<rest-of-private-key>
Loaded address: 0x8be6c8126c4383745c25f3b3ca76d73e3caf8544
Error occurred while sending a tx - Error: insufficient funds for intrinsic transaction cost [ See: https://links.ethers.org/v5-errors-INSUFFICIENT_FUNDS ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":57,\"error\":{\"code\":-32000,\"message\":\"insufficient funds for gas * price + value\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f8708189508555d3a0de488555d3a0de4882520894b4de0833771eae55040b698af5eb06d59e142c828316916880c001a09d2caa5ace2bf82aab0d13fdabf8617f9e41d6bab5d3023f9606147786f1a282a04fba6befe738517b9c3eedb89ec0c8768018d84dd348636dc4dc1806db1987e6\"],\"id\":57,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://polygon-rpc.com/"}, method="sendTransaction", transaction="0x02f8708189508555d3a0de488555d3a0de4882520894b4de0833771eae55040b698af5eb06d59e142c828316916880c001a09d2caa5ace2bf82aab0d13fdabf8617f9e41d6bab5d3023f9606147786f1a282a04fba6befe738517b9c3eedb89ec0c8768018d84dd348636dc4dc1806db1987e6", code=INSUFFICIENT_FUNDS, version=providers/5.7.2)
Error whilst funding: insufficient funds for intrinsic transaction cost [ See: https://links.ethers.org/v5-errors-INSUFFICIENT_FUNDS ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":57,\"error\":{\"code\":-32000,\"message\":\"insufficient funds for gas * price + value\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f8708189508555d3a0de488555d3a0de4882520894b4de0833771eae55040b698af5eb06d59e142c828316916880c001a09d2caa5ace2bf82aab0d13fdabf8617f9e41d6bab5d3023f9606147786f1a282a04fba6befe738517b9c3eedb89ec0c8768018d84dd348636dc4dc1806db1987e6\"],\"id\":57,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://polygon-rpc.com/"}, method="sendTransaction", transaction="0x02f8708189508555d3a0de488555d3a0de4882520894b4de0833771eae55040b698af5eb06d59e142c828316916880c001a09d2caa5ace2bf82aab0d13fdabf8617f9e41d6bab5d3023f9606147786f1a282a04fba6befe738517b9c3eedb89ec0c8768018d84dd348636dc4dc1806db1987e6", code=INSUFFICIENT_FUNDS, version=providers/5.7.2)
error.txt
3 KB
Here's the wallet on polygonscan. Like said, it has some funds, and the funds it has is >> the funds it's trying to send to bundlr. https://polygonscan.com/address/0x8bE6c8126C4383745c25F3b3Ca76D73E3Caf8544
Polygon (MATIC) Blockchain Explorer
[Address 0x8bE6c8126C4383745c25F3b3Ca76D73E3Caf8544 | PolygonScan](https://polygonscan.com/address/0x8bE6c8126C4383745c25F3b3Ca76D73E3Caf8544)
The Address 0x8bE6c8126C4383745c25F3b3Ca76D73E3Caf8544 page allows users to view transactions, balances, token holdings and transfers of both ERC-20 and ERC-721 (NFT) tokens, and analytics.
Image
Idea: perhaps polygon or bundlr has some minimum threshold of funds needed, to even bother with a tx. To test this, I tried the CLI command with a wallet having more funds (>$100 of MATIC). It worked!
Details of successful run
bundlr fund 1479016 -h https://node1.bundlr.network/ --no-confirmation -c matic -w bc4ee<rest-of-private-key>
Loaded address: 0xf5dcd98a1c99c2c65c62025cb23cfb6f12f35497
Funding receipt: 
Amount: 1479016 with Fee: "671189180214000" to 0xb4DE0833771eae55040b698aF5eB06d59E142C82 
Transaction ID: 0xde6f95916396116f5a53e3452bd9eff56cbd5af5b4e3fee64cf7b3dc917874e8 
success.txt
1 KB
Jesse — Today at 1:06 PM
less this, more that the network fees for matic are pretty high (we also add a multiplier to them to prevent the error you initially encountered)
trentmc0 — Today at 1:06 PM
Yeah, that could be the issue.
The network fee for the tx that just happened was: 0.000000000001479016 MATIC (< $0.000001)
tx: https://polygonscan.com/tx/0xde6f95916396116f5a53e3452bd9eff56cbd5af5b4e3fee64cf7b3dc917874e8
So the other address should have had more than enough. It held 0.000981761157456348 MATIC. https://polygonscan.com/address/0x8bE6c8126C4383745c25F3b3Ca76D73E3Caf8544
Jesse — Today at 1:08 PM
that's the resultant fee, but not the one we tried to use
trentmc0 — Today at 1:09 PM
For me, at least now I have an actionable path forward: just make sure my wallets have more funds
Jesse — Today at 1:09 PM
look at the max fee per gas 
and you'll see that it's very high - the tx wil fail if you can't cover the gas limit * the max gas fee
trentmc0 — Today at 1:09 PM
OK. It's: 0.00000031961389534 MATIC
trentmc0 — Today at 1:09 PM
Yep
Jesse — Today at 1:09 PM
yeah so times that by 21,000 
trentmc0 — Today at 1:10 PM
And I guess that explains it!
This is fine.
Jesse — Today at 1:10 PM
yup
trentmc0 — Today at 1:10 PM
Now I have an actionable path forward too:)
Jesse — Today at 1:10 PM
👍
trentmc0 — Today at 1:11 PM
I guess if you guys wanted, the bundlr error message could be better, explaining how much MATIC was actually needed. Though TBH most people will probably have a good margin of MATIC in their wallet? So probably not a high priority

[error.txt](https://github.com/oceanprotocol/pybundlr/files/10077318/error.txt)

[success.txt](https://github.com/oceanprotocol/pybundlr/files/10077300/success.txt)
