### ISSUE TITLE
Reduce friction in the integration with bundlr -- remove global install

### ISSUE THREAD

**Issue by juanpablovs** [oceanprotocol/pybundlr#7]
### Background / motivation

Pybundlr currently uses use bundlr's CLI. bundlr's CLI needs to be installed globally via node. This creates many problems for users. Perhaps most notably, in node, the  default installation does not allow for global installs.

A solution would be to find a way to execute bundlr's CLI without a global install

### Candidate solutions

1. Rewrite pybundlr in node
2. Execute a python subprocess that is fetched with a js file
3. Use bundlr's REST API
4. Use bundlr's JS SDK. Via tools to wrap JS with Py, such sa [JSPyBridge](https://blog.logrocket.com/exploring-jspybridge-library-python-javascript/) or [PyScript](https://www.jhanley.com/blog/pyscript-javascript-and-python-interoperability/)
5. (Remove the need for bundlr in our use case)

### Analysis of candidates

> 1. Rewrite pybundlr in node

There is already a bundlr JS SDK. The point of pybundlr is the "py" part: to be readily accessible in python

> 2. Execute a python subprocess that is fetched with a js file

This needs elaboration. Feels like a lot of moving parts though

> 3. Use bundlr's REST API

As of Nov 2022, this is poorly documented. Not clear how to use it. If we really needed, however, we could see if & how the Bundlr JS SDK uses it
 
> 4. Use bundlr's JS SDK

Promising, should explore more

> 5. (Remove the need for bundlr in our use case)

Our (Ocean's) main use case for pybundlr was [Predict-ETH Challenge](https://github.com/oceanprotocol/predict-eth).

As of [late Feb 2023](https://github.com/oceanprotocol/pybundlr/issues/7#issuecomment-1448045414), for [Predict-ETH Round 4](https://github.com/oceanprotocol/predict-eth/blob/main/challenges/main4.md), we removed the need for bundlr. 

This has lowered the priority of this issue for Ocean.

**Comment by trentmc** [comment]
> possible solution: rewrite pybundlr in node

FYI there is already a bundlr JS SDK. 

The point of pybundlr is the "py" part: to be readily accessible in python

> execute a python subprocess that is fetched with a js file

Please elaborate. FYI there's a python library called "javascript" that makes JS code look like a python library. So one option would be to wrap the bundlr SDK this way.

> see if bundlr's API works so we can replace the CLI

this is the simplest

**Comment by trentmc** [comment]
JP & I discussed: we're going with using JS <> py integration

**Comment by trentmc** [comment]
> using JS <> py integration

Here are a couple recent blog posts of interest, each showing a JS <> py integratoin. 

- Sep 2022 - "Exploring JSPyBridge, a new library for using Python in JavaScript" https://blog.logrocket.com/exploring-jspybridge-library-python-javascript/
- Aug 2022 - "PyScript: JavaScript and Python Interoperability" https://www.jhanley.com/blog/pyscript-javascript-and-python-interoperability/

**Comment by trentmc** [comment]
https://github.com/oceanprotocol/pybundlr/tree/replace-cli-with-javascript-sdk

**Comment by trentmc** [comment]
Low priority for predict-eth, because we're using ERC725 for now.
